#!/bin/bash
ETHERNET_LAST_RECEIVED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 10)
ETHERNET_LAST_TRANSMITTED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 53)
LO_LAST_RECEIVED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 7)
LO_LAST_TRANSMITTED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 49)
WLAN_LAST_RECEIVED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 3)
WLAN_LAST_TRANSMITTED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 44)
sleep 1
WLAN_TRANSMITTED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 44)
WLAN_RECEIVED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 3)
LO_RECEIVED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 7)
LO_TRANSMITTED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 49) 
ETHERNET_RECEIVED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 10)
ETHERNET_TRANSMITTED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 53)
echo $((WLAN_RECEIVED-WLAN_LAST_RECEIVED)) >> wlanreceived.data
echo $((WLAN_TRANSMITTED-WLAN_LAST_TRANSMITTED)) >> wlantransmitted.data
echo $((LO_RECEIVED-LO_LAST_RECEIVED)) >> loreceived.data
echo $((LO_TRANSMITTED-LO_LAST_TRANSMITTED)) >> lotransmitted.data
echo $((ETHERNET_TRANMSITTED-ETHERNET_LAST_TRANSMITTED)) >> ethernettransmitted.data
echo $((ETHERNET_RECEIVED-ETHERNET_LAST_RECEIVED)) >> ethernetreceived.data
WLAN_LAST_TRANSMITTED=$WLAN_TRANSMITTED
WLAN_LAST_RECEIVED=$WLAN_RECEIVED
WLAN_TRANSMITTED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 44)
WLAN_RECEIVED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 3)
LO_LAST_TRANSMITTED=$LO_TRANSMITTED
LO_LAST_RECEIVED=$LO_RECEIVED
LO_RECEIVED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 7)
LO_TRANSMITTED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 49)
ERHERNET_LAST_TRANSMITTED=$ETHERNET_TRANSMITTED
ETHERNET_LAST_RECEIVED=$ETHERNET_RECEIVED
ETHERNET_RECEIVED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 10)
while getopts ":i:" opt; do
if [ "$OPTARG" == "wlan" ]
then
#WLAN-TRANSMITTED PART

if [ "$3" == "-t" ]
then
echo "WLAN TRANSMITTED Selected"
while [ "$REPLY" != "Q" ] 
do
WLAN_LAST_TRANSMITTED=$WLAN_TRANSMITTED
WLAN_TRANSMITTED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 44)
echo $((WLAN_TRANSMITTED-WLAN_LAST_TRANSMITTED)) >> wlantransmitted.data
gnuplot << !
set title "Transmission Data Monitor"
set xlabel "Time"
set terminal dumb 135 37
plot "wlantransmitted.data" with lines  
reread
!
read -t 1
clear
echo "WLAN TRANSMITTED : $WLAN_TRANSMITTED"
echo "WLAN TRANSMISSION DIFFRECE : $((WLAN_TRANSMITTED-WLAN_LAST_TRANSMITTED))"
done

#END OF WLAN TRANSMITTED
#WLAN RECEIVED PART
elif [ "$3" == "-r" ]
then
echo "WLAN RECEIVED selected"
while [ "$REPLY" != "Q" ]
do
WLAN_LAST_RECEIVED=$WLAN_RECEIVED
WLAN_RECEIVED=$(cat /proc/net/dev | tail -n 1 | cut -d " " -f 3)
echo $WLAN_RECEIVED
echo $((WLAN_RECEIVED-WLAN_LAST_RECEIVED)) >> wlanreceived.data
gnuplot << !
set title "WLAN Received Data Monitor"
set xlabel "Time"
set terminal dumb 135 37
plot "wlanreceived.data"  with lines
reread
!
read -t 1  
clear
echo "WLAN RECIVED : $WLAN_RECEIVED"
echo "WLAN LAST_RECEIVED : $WLAN_LAST_RECEIVED"
echo "WLAN RECEIVED Difference : $((WLAN_RECEIVED-WLAN_LAST_RECEIVED))"
done
#END OF WLAN RECEIVED
else
#WLAN INVALID
echo "INVALID OPTION"
#WLAN INVALID END
fi
#WLAN END
#LO BEGIN
elif [ "$OPTARG" = "lo" ] 
then
if [ "$3" == "-t" ]
then
#BEGIN LO TRANSMITTED
echo "LO TRANSMITTED SELECTED"
while [ "$REPLY" != "Q" ]
do
LO_LAST_TRANSMITTED=$LO_TRANSMITTED
LO_TRANSMITTED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 49)
echo $LO_TRANSMITTED
echo $((LO_TRANSMITTED-LO_LAST_TRANSMITTED)) >> lotransmitted.data
gnuplot << !
set title "LO Transmitted Data Monitor"
set xlabel "Time"
set terminal dumb 135 37
plot "lotransmitted.data" with lines
reread
!
read -t 1
clear
echo "LO TRANSMITTED : $LO_TRANSMITTED"
echo "LO LAST_TRANSMITTED : $LO_LAST_TRANSMITTED"
echo "LO TRANSMITTED DIFFERENCE : $((LO_TRANSMITTED-LO_LAST_TRANSMITTED))"
done
#END LO TRANSMITTED
#BEGIN LO RECEIVED
elif [ "$3" == "-r" ]
then
echo "LO RECEIVED SELECTED"
while [ "$REPLY" != "Q" ]
do
LO_LAST_RECEIVED=$LO_RECEIVED
LO_RECEIVED=$(cat /proc/net/dev | tail -n 2 | head -n 1 | cut -d " " -f 7)
echo $LO_RECEIVED
echo $((LO_RECEIVED-LO_LAST_RECEIVED)) >> loreceived.data
gnuplot << !
set title "LO Received Data Monitor"
set xlabel "Time"
set terminal dumb 135 37
plot "loreceived.data" with lines
reread
!
read -t 1
clear
echo "LO RECEIVED : $LO_RECEIVED"
echo "LO LAST_RECEIVED : $LO_LAST_RECEIVED"
echo "LO RECEIVE DIFFENCE : $((LO_RECEIVED-LO_LAST_RECEIVED))"
done
else
echo "Invalid option you can enter only -r or -t"
fi
#END LO RECEIVED
#END LO
#BEGIN ETHERNET
elif [ "$OPTARG" == "eth" ]
then
if [ "$3" == "-t" ]
then
#BEGIN TRANSMISSION RECEIVED
echo "ETHERNET TRANSMITTED SELECTED"
while [ "$REPLY" != "Q" ]
do
ETHERNET_LAST_TRANSMITTED=$ETHERNET_TRANSMITTED
ETHERNET_TRANSMITTED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 53)
echo $ETHERNET_TRANSMITTED
echo $((ETHERNET_TRANSMITTED-ETHERNET_LAST_TRANSMITTED)) >> ethernettransmitted.data
gnuplot << !
set title "Ethernet Transmitted Data Monitor"
set xlabel "Time"
set terminal dumb 135 37
plot "ethernettransmitted.data" with lines
reread
!
read -t 1
clear
echo "ETHERNET TRANSMITTED : $ETHERNET_TRANSMITTED"
echo "ETHERNET LAST_TRANSMITTED : $ETHERNET_LAST_TRANSMITTED"
echo "ETHERNET TRANSMISSION DIFFERENCE : $((ETHERNET_TRANSMITTED-ETHERNET_LAST_TRANSMITTED))"
done

#ETHERNET TRANSMISSION END
#ETHERNET RECEIVED BEGIN
elif [ "$3" == "-r" ]
then
echo "ETHERNET RECEIVED SELECTED"
while [ "$REPLY" != "Q" ]
do
ETHERNET_LAST_RECEIVED=$ETHERNET_RECEIVED
ETHERNET_RECEIVED=$(cat /proc/net/dev | tail -n 3 | head -n 1 | cut -d " " -f 10)
echo $ETHERNET_RECEIVED
echo $((ETHERNET_RECEIVED-ETHERNET_LAST_RECEIVED)) >> ethernetreceived.data
gnuplot << !
set title "Ethernet Received Data Monitor"
set xlabel "Time"
set terminal dumb 135 37
plot "ethernetreceived.data" with lines
reread
!
read -t 1
clear
echo "ETHERNET RECEIVED : $ETHERNET_RECEIVED"
echo "ETHERNET LAST_RECEIVED :$ETHERNET_LAST_RECEIVED"
echo "ETHERNET RECEIVE DIFFERENCE :$((ETHERNET_RECEIVED-ETHERNET_LAST_RECEIVED))"
done
else
echo "Invalid option you can only select -r or -t"
fi
fi

done




